### PR TITLE
Add support for file streams as input.

### PR DESCRIPTION
**Pull request by maxlang**
I'm honestly not sure who's currently maintaining this repo, but based on a comment [here](https://github.com/tcr/scissors/issues/7) I thought maybe you guys were. I also noticed a bunch of recent activity [here](https://github.com/justsml/scissors) though of course none of this will make it into npm unless someone merges into tcr/scissors.

I'm happy to clean this up a bit, but basically it checks if the input appears to be a stream and, if so, it streams that to the command instead of giving it a filename.

### CODE REVIEW

**Comment by rikkertkoppes** [comment]
Sounds promising. I'll look into it. but it'd at least need some amendments to readme. A few comments in the code would also be nice.

**Comment by rikkertkoppes** [comment]
Reviewed and happy to merge. Before doing that, could you amend the readme to reflect your changes?

**Comment by maxlang** [comment]
Sure! Sorry for the slow reply - I missed the earlier comment. I'll update the README

**Comment by maxlang** [comment]
Closing this PR since it looks like other changes got merged in and I'm not intending to keep working on it.

**Pull request closed without merging**
